{{- if and .Values.bullmqExporter.enabled .Values.bullmqExporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bullmq-exporter
  {{- if .Values.bullmqExporter.serviceMonitor.namespace }}
  namespace: {{ .Values.bullmqExporter.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "bullmq.labels" . | nindent 4 }}
    {{- if .Values.bullmqExporter.serviceMonitor.labels }}
    {{- toYaml .Values.bullmqExporter.serviceMonitor.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.bullmqExporter.serviceMonitor.annotations }}
  annotations:
    {{- toYaml .Values.bullmqExporter.serviceMonitor.annotations | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.bullmqExporter.serviceMonitor.interval }}
    {{- if .Values.bullmqExporter.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.bullmqExporter.serviceMonitor.scrapeTimeout }}
    {{- end }}
    honorLabels: true
    port: metrics
    path: {{ .Values.bullmqExporter.serviceMonitor.path }}
    scheme: {{ .Values.bullmqExporter.serviceMonitor.scheme }}
    {{- if .Values.bullmqExporter.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{- toYaml .Values.bullmqExporter.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.bullmqExporter.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml .Values.bullmqExporter.serviceMonitor.relabelings | nindent 6 }}
    {{- end }}
  jobLabel: "{{ .Release.Name }}-bullmq"
  selector:
    matchLabels:
      {{- include "bullmq.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
