{{- if eq .Values.config.SWARM_CHUNKSTORM_ENABLED "true" }}
apiVersion: v1
kind: Service
metadata:
  name: chunkstorm
  labels:
    {{- include "chunkstorm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.chunkstorm.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.chunkstorm.service.port | default 3050 }}
      protocol: TCP
      targetPort: 3050
  selector:
    {{- include "chunkstorm.selectorLabels" . | nindent 4 }}
{{- end }}
