{{- if eq .Values.config.SWARM_CHUNKSTORM_ENABLED "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunkstorm
  labels:
    {{- include "chunkstorm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chunkstorm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chunkstorm.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "blobscan.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: chunkstorm
          image: "{{ .Values.chunkstorm.repository }}:{{ .Values.chunkstorm.tag }}"
          imagePullPolicy: {{ .Values.chunkstorm.pullPolicy }}
          ports:
            - name: http
              containerPort: 3050
              protocol: TCP
          resources:
            {{- toYaml .Values.chunkstorm.resources | nindent 12 }}
          env:
            - name: BATCH_ID
              value: {{ .Values.config.SWARM_BATCH_ID | quote }}
            - name: KEYSTORE_PATH
              value: {{ .Values.chunkstorm.keystorePath | quote }}
            - name: KEYSTORE_PASSWORD
              value: {{ .Values.chunkstorm.keystorePassword | quote }}
            - name: BEE_ENDPOINT
              value: {{ .Values.config.BEE_ENDPOINT | quote }}
            - name: STAMPERSTORE_PATH
              value: {{ .Values.chunkstorm.stamperstorePath | quote }}
          volumeMounts:
            - name: stamperstore
              mountPath: {{ .Values.chunkstorm.stamperstorePath }}
            - name: keystore
              mountPath: {{ .Values.chunkstorm.keystorePath }}
              subPath: keystore.json
      volumes:
        - name: stamperstore
        {{- if .Values.chunkstorm.stamperstorePersistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: stamperstore
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: keystore
          secret:
            secretName: chunkstorm-keystore
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
