apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blobscan.fullname" . }}
  labels:
    {{- include "blobscan.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "blobscan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blobscan.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "blobscan.serviceAccountName" . }}
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      initContainers:
      {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{- if gt (len .Values.customCommand) 0 }}
            {{- toYaml .Values.customCommand | nindent 12}}
          {{- else }}
            {{- if gt (len .Values.args) 0 }}
            {{- toYaml .Values.args | nindent 12}}
            {{- end }}
          {{- end }}
          {{- if gt (len .Values.customArgs) 0 }}
          args:
            {{- toYaml .Values.customArgs | nindent 12}}
          {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            {{- if .Values.extraVolumeMounts }}
              {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ include "blobscan.httpPort" . }}
              protocol: TCP
            {{- if .Values.extraPodPorts }}
              {{ toYaml .Values.extraPodPorts | nindent 10 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CHAIN_ID
              value: {{ .Values.config.CHAIN_ID | quote }}
            - name: DATABASE_URL
              value: {{ .Values.config.DATABASE_URL | quote }}
            - name: REDIS_URI
              value: {{ .Values.config.REDIS_URI | quote }}
            - name: SECRET_KEY
              value: {{ .Values.config.SECRET_KEY | quote }}
            - name: NETWORK_NAME
              value: {{ .Values.config.NETWORK_NAME | quote }}
            - name: BLOBSCAN_API_BASE
              value: {{ .Values.config.BLOBSCAN_API_BASE | quote }}
            - name: BLOBSCAN_API_PORT
              value: {{ .Values.httpPort | quote }}
            - name: POSTGRES_STORAGE_ENABLED
              value: {{ .Values.config.POSTGRES_STORAGE_ENABLED | quote }}
            - name: SWARM_STORAGE_ENABLED
              value: {{ .Values.config.SWARM_STORAGE_ENABLED | quote }}
            - name: GOOGLE_STORAGE_ENABLED
              value: {{ .Values.config.GOOGLE_STORAGE_ENABLED | quote }}
            - name: GOOGLE_STORAGE_BUCKET_NAME
              value: {{ .Values.config.GOOGLE_STORAGE_BUCKET_NAME | quote }}
            - name: GOOGLE_STORAGE_PROJECT_ID
              value: {{ .Values.config.GOOGLE_STORAGE_PROJECT_ID | quote }}
            - name: GOOGLE_SERVICE_KEY
              value: {{ .Values.config.GOOGLE_SERVICE_KEY | quote }}
            - name: OTLP_AUTH_USERNAME
              value: {{ .Values.config.OTLP_AUTH_USERNAME | quote }}
            - name: OTLP_AUTH_PASSWORD
              value: {{ .Values.config.OTLP_AUTH_PASSWORD | quote }}
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: {{ .Values.config.OTEL_EXPORTER_OTLP_PROTOCOL | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.config.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
            - name: METRICS_ENABLED
              value: {{ .Values.config.METRICS_ENABLED | quote }}
            - name: TRACES_ENABLED
              value: {{ .Values.config.TRACES_ENABLED | quote }}
            - name: BEE_ENDPOINT
              value: {{ .Values.config.BEE_ENDPOINT | quote }}
          {{- range $key, $value := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "blobscan.fullname" $ }}-env
                  key: {{ $key }}
          {{- end }}
          {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
      {{- if .Values.extraContainers }}
        {{ toYaml .Values.extraContainers | nindent 8}}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
      {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8}}
      {{- end }}
