{{- if .Values.chunkstorm.stamperstorePersistentVolume.enabled }}
# TODO: No eliminar este recurso si se pone
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stamperstore
  labels:
    {{- include "chunkstorm.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.chunkstorm.stamperstorePersistentVolume.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.chunkstorm.stamperstorePersistentVolume.size }}
  {{- if .Values.chunkstorm.stamperstorePersistentVolume.storageClassName }}
  storageClassName: {{ .Values.chunkstorm.stamperstorePersistentVolume.storageClassName }}
  {{- end }}
{{- end }}
