apiVersion: v2
name: blobscan-api
description: Blobscan tRPC API
home: https://blobscan.com
icon: https://raw.githubusercontent.com/Blobscan/blobscan/next/.github/assets/blobi.jpeg
sources:
  - https://github.com/blobscan/blobscan/
type: application
version: 0.2.0
maintainers:
  - name: samcm
    email: sam.calder-mason@ethereum.org
  - name: PabloCastellano
    email: pablo@anche.no
