apiVersion: v2
name: blobscan
version: 0.3.0
description: Blobscan is the first blockchain explorer that helps to navigate and visualize those EIP-4844 blobs
type: application
keywords:
  - ethereum
  - eip4844
  - blobs
home: https://blobscan.com
sources:
  - https://github.com/blobscan/blobscan/
dependencies:
- name: postgresql
  repository: "https://charts.bitnami.com/bitnami"
  version: 15.5.20
  alias: blobscandb
  condition: blobscandb.enabled
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 19.6.4
  alias: redis
  condition: redis.enabled
maintainers:
  - name: PabloCastellano
    email: pablo@anche.no
icon: https://raw.githubusercontent.com/Blobscan/blobscan/main/.github/assets/logo.svg
