apiVersion: v2
name: blobscan
version: 0.9.8
description: Blobscan meta-chart (depends on blobscan-api, blobscan-web and blobscan-indexer)
type: application
keywords:
  - ethereum
  - eip4844
  - blobs
home: https://blobscan.com
sources:
  - https://github.com/blobscan/blobscan/
dependencies:
- name: blobscan-web
  repository: "file://../blobscan-web"
  version: 0.6.0
  condition: blobscan-web.enabled
- name: blobscan-api
  repository: "file://../blobscan-api"
  version: 0.6.9
  condition: blobscan-api.enabled
- name: blobscan-indexer
  repository: "file://../blobscan-indexer"
  version: 0.4.0
  condition: blobscan-indexer.enabled
- name: postgresql
  repository: "https://charts.bitnami.com/bitnami"
  version: 15.5.20
  alias: blobscandb
  condition: blobscandb.enabled
- name: redis
  repository: "https://charts.bitnami.com/bitnami"
  version: 19.6.4
  # version: 20.11.3
  alias: redis
  condition: redis.enabled
maintainers:
  - name: PabloCastellano
    email: pablo@anche.no
icon: https://raw.githubusercontent.com/Blobscan/blobscan/main/.github/assets/logo.svg
