apiVersion: v2
name: blobscan
description: Blobscan is the first blockchain explorer that helps to navigate and visualize those EIP-4844 blobs
home: https://blobscan.com
icon: https://raw.githubusercontent.com/Blobscan/blobscan/next/.github/assets/blobi.jpeg
sources:
  - https://github.com/blobscan/blobscan/
type: application
version: 0.2.11
maintainers:
  - name: PabloCastellano
    email: pablo@anche.no
dependencies:
- name: postgresql
  repository: "https://charts.bitnami.com/bitnami"
  version: "11.9.13"
  alias: blobscandb
  condition: blobscandb.enabled
