apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blobscan-dagster.fullname" . }}-instance
  labels:
    {{- include "blobscan-dagster.labels" . | nindent 4 }}
data:
  dagster.yaml: |
    scheduler:
      module: dagster.core.scheduler
      class: DagsterDaemonScheduler

    run_coordinator:
      module: dagster.core.run_coordinator
      class: QueuedRunCoordinator
      config:
        max_concurrent_runs: {{ .Values.dagsterInstance.maxConcurrentRuns }}

    run_launcher:
      module: dagster_k8s
      class: K8sRunLauncher
      config:
        service_account_name: {{ include "blobscan-dagster.serviceAccountName" . }}
        job_namespace: {{ .Release.Namespace }}
        env_vars:
          - DAGSTER_POSTGRES_USER
          - DAGSTER_POSTGRES_PASSWORD
          - DAGSTER_POSTGRES_DB
          - DAGSTER_POSTGRES_HOST
          - DAGSTER_POSTGRES_PORT

    run_storage:
      module: dagster_postgres.run_storage
      class: PostgresRunStorage
      config:
        postgres_db:
          hostname:
            env: DAGSTER_POSTGRES_HOST
          username:
            env: DAGSTER_POSTGRES_USER
          password:
            env: DAGSTER_POSTGRES_PASSWORD
          db_name:
            env: DAGSTER_POSTGRES_DB
          port:
            env: DAGSTER_POSTGRES_PORT

    schedule_storage:
      module: dagster_postgres.schedule_storage
      class: PostgresScheduleStorage
      config:
        postgres_db:
          hostname:
            env: DAGSTER_POSTGRES_HOST
          username:
            env: DAGSTER_POSTGRES_USER
          password:
            env: DAGSTER_POSTGRES_PASSWORD
          db_name:
            env: DAGSTER_POSTGRES_DB
          port:
            env: DAGSTER_POSTGRES_PORT

    event_log_storage:
      module: dagster_postgres.event_log
      class: PostgresEventLogStorage
      config:
        postgres_db:
          hostname:
            env: DAGSTER_POSTGRES_HOST
          username:
            env: DAGSTER_POSTGRES_USER
          password:
            env: DAGSTER_POSTGRES_PASSWORD
          db_name:
            env: DAGSTER_POSTGRES_DB
          port:
            env: DAGSTER_POSTGRES_PORT
