apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blobscan-ipld.fullname" . }}-env
  labels:
    {{- include "blobscan-ipld.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secretEnv }}
{{- if ne $value "" }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
