apiVersion: v1
kind: Service
metadata:
  name: {{ include "blobscan-ipld.fullname" . }}
  labels:
    {{- include "blobscan-ipld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
    {{- if .Values.extraPorts }}
    {{- toYaml .Values.extraPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "blobscan-ipld.selectorLabels" . | nindent 4 }}
