global:
  main:
    network: 4844-devnet-5
    engineEndpoint: http://{{ .Release.Name }}-execution:8551
    rpcEndpoint: http://{{ .Release.Name }}-execution:8545
    beaconEndpoint: http://{{ .Release.Name }}-beacon:5052
  checkpointSync:
    enabled: false
#Geth
geth:
  fullnameOverride: geth-prysm-001
  enabled: true
  image:
    repository: ethpandaops/geth
    tag: mdehoog-eip4844-7d7c642
  p2pNodePort:
    enabled: true
    port: 31888
  persistence:
    enabled: true
    size: 50Gi
  podLabels:
    network: 4844-devnet-5
    testnet: 4844-devnet-5
    ethereum_network: 4844-devnet-5
    ethereum_role: execution
    consensus_client: prysm
    execution_client: geth
    ethereum_instance: geth-prysm-001
  resources:
    requests:
      cpu: 2000m
      memory: 5Gi
    limits:
      cpu: 3000m
      memory: 7Gi
  extraArgs:
    - --bootnodes "enode://304ca79ed7ae81492d4c9e5513bebbfd2b113751b85b54821e5be176e56190159a25c227ceaffef1e02772642ec1f514724687a06001487091e15429049a4bb0@134.209.199.102:30303,enode://a9343d22b0cc076f87916e22ce21ef484451255bfcf7dc88f93d301b63b2a8c0ffdaad753c35d9ab65679dd84a563c77ea06f03e1a5c9df95723f4dc3c611b73@134.209.87.158:30303,enode://3bfd19e7fe40f1742e7ddb09964e2af1a69a164ef8fcedbd92adbabf4008f74986c6482a2dda17f7beb5e9ab94c300d800c65b2efb59d21f5e8b23364172b655@164.92.222.131:30303,enode://01b12eb19f1a26a0d3b87b7cc04163d8c1ac7788fdfc462af3e4b17d5af422193be44e976c67117de78e0c095703bfa98bf25c729cf8861ef2d6d8af5339a914@104.248.93.148:30303,enode://1206690a90e33d66f18ec9d281ef683897c3320d3aa54ae97c3ca7a6126c01c68038fd6169265839ced539bce0b8daa289b8f8e6798bad7610db552f45b5b1f2@164.92.209.217:30303,enode://9719bd60e5188a4da960eb9038c9fc927edc6d1f6e05c65fe0662b0a8821e6d22170cbe46e343f2f2bacce6fb6eb2a8eed6ccd37d9fbe65464fe005f5cc3ea25@134.209.193.205:30303,enode://e754dbad1faf75311dda4cc900f034ae5eb557641a4ea5557fbd53528e8b93563e6f3813e9181453fcd2b3a426a498625c89a6925fd7d65a289632c0392b2ac4@164.92.213.18:30303,enode://f8ae3f4a346d14af151881a658868a35572b954441a3da96e898b3f8cefeb7821070ecf5029cbabbf943542af3021a2add18b7d54e0a587536bc91b1d23c4484@134.209.197.126:30303,enode://0eeaa41c7644ba0eebf9ee9d58dd5e17a780b27f161f45a5969ecc757e85531fbe102b5a6ad9b50d26e2f48d24dcb66bafce62017f3770502783ff83d5f60d9b@134.209.201.29:30303,enode://4663cf61dbf508575274d6f807fee1889a257579c0209bd602e1b388ed189fea69d2c5be944e3c22713b0c4a43ab3c5fd6306dded0b0f24e4c556f93ff800fff@167.71.77.73:30303,enode://f600e843d55504b2975f2748aad01be02612b6cb5243422a8c52385da6682b771e112f86c072efdcded098dc10cff006f5ee1a54e6a12221220d6399f663fc3b@164.92.145.125:30303,enode://65ca2cb1c508b7ff010444aeee1c67af043faabb5372fd24e7b62ba3b621cf3fa6c4324d20ce51ac50855711843c4dd414e9d2fdfe193b7b3a1187788207541a@134.209.203.125:30303"
    - --networkid="$(cat /data/chainid.txt)"
    - --ws.api="eth,net,engine,web3,txpool"
    - --http.api="eth,net,engine,web3,txpool"
    - --syncmode=full
    - --gcmode archive
  initContainers:
  - name: init-genesis
    image: ethpandaops/geth:mdehoog-eip4844-7d7c642
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    command:
      - sh
      - -ace
      - >
        GENESIS_URI=https://config.4844-devnet-5.ethpandaops.io/el/genesis.json;
        if ! [ -f /data/genesis_init_done ];
        then
          wget -O /data/genesis.json $GENESIS_URI;
          apk update && apk add jq;
          cat /data/genesis.json | jq -r '.config.chainId' > /data/chainid.txt;
          geth init --datadir /data /data/genesis.json;
          touch /data/genesis_init_done;
          echo "genesis init done";
        else
          echo "genesis is already initialized";
        fi;
    volumeMounts:
      - name: storage
        mountPath: "/data"
# Prysm
prysm:
  fullnameOverride: prysm-geth-001
  enabled: true
  image:
    repository: ethpandaops/prysm
    tag: eip4844-8efb57c
    pullPolicy: Always
  mode: "beacon"
  podLabels:
    network: 4844-devnet-5
    testnet: 4844-devnet-5
    ethereum_network: 4844-devnet-5
    ethereum_role: consensus
    consensus_client: prysm
    execution_client: geth
    ethereum_instance: geth-prysm-001
  resources:
    requests:
      cpu: 2000m
      memory: 5Gi
    limits:
      cpu: 3000m
      memory: 7Gi
  p2pNodePort:
    enabled: false
    startsAt: 31004
  persistence:
    enabled: true
    size: 50Gi
  extraArgs:
    - --execution-endpoint=http://geth-prysm-001:8551
    - --bootstrap-node="enr:-Iq4QAw-ZQb0IiosZgDDcK5ehLs1XmwT0BWU1E1W3ZnhlAAwAE3I46dgCsCbeB5QUwcpDmpFfveTfKF7-tiIg0KWGjqGAYXoIfe6gmlkgnY0gmlwhKEjXcqJc2VjcDI1NmsxoQN4HpB2GMFY2MzwO9hGFjqRG47OX4hGDliAG-mJNWkEr4N1ZHCCIyk"
    - --bootstrap-node="enr:-MS4QDPpPzkDJ65iCq9dthJZ5p49OljTrtbHN_D3f97T-BKjNMdd2MQi4Vu7N--dmotiLZDgiw8BnrdDxkd_ICgvneIHh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCzMmyVQEhEBQEAAAAAAAAAgmlkgnY0gmlwhIbRx2aJc2VjcDI1NmsxoQJoQoV-vbiuItOSCsczcQ9vvL_IoaNaslVeqUpnyxP0jYhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo"
    - --bootstrap-node="enr:-Ly4QAncaUrjSVfGXB1hve34TtNOMUNKzL_QFD3c1kgbrh6raYEbXFfojLIRi_0cR29HsARtxVmNWFmXrDLwK1IwmZ0Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCzMmyVQEhEBQEAAAAAAAAAgmlkgnY0gmlwhIbRV56Jc2VjcDI1NmsxoQMQ_2uv2pI_3AWzLFpb65WCPrcdLbktj0mjqdn-oHIU3YhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
    - --bootstrap-node="enr:-Ly4QAJiM67BYojGl6J_zkbbXOzhHRunz8-AkqpLGcF9QlehL3X8RJbT5ALDSrmkn29CEqbKvszxxOHvs36654OntJ8Lh2F0dG5ldHOI__________-EZXRoMpA9CJoRUEhEBf__________gmlkgnY0gmlwhKRc1RKJc2VjcDI1NmsxoQKhKGNYCtzZf4XJNKqcrOFrQLoKJ68weh1tHsdJE2XAwYhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA"
    - --genesis-state=/data/testnet_spec/genesis.ssz
    - --chain-config-file=/data/testnet_spec/config.yaml
  initContainers:
  - name: init-genesis
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    command:
      - sh
      - -ace
      - >
        DEPOSIT_CONTRACT_URI=https://config.4844-devnet-5.ethpandaops.io/deposit_contract.txt;
        DEPOSIT_CONTRACT_BLOCK_URI=https://config.4844-devnet-5.ethpandaops.io/cl/deposit_contract_block.txt;
        DEPLOY_BLOCK_URI=https://config.4844-devnet-5.ethpandaops.io/cl/deploy_block.txt;
        GENESIS_CONFIG_URI=https://config.4844-devnet-5.ethpandaops.io/cl/config.yaml;
        GENESIS_SSZ_URI=https://config.4844-devnet-5.ethpandaops.io/cl/genesis.ssz;
        BOOTNODE_URI=https://config.4844-devnet-5.ethpandaops.io/bootstrap_nodes.txt;
        mkdir -p /data/testnet_spec;
        if ! [ -f /data/testnet_spec/genesis.ssz ];
        then
          wget -O /data/testnet_spec/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
          wget -O /data/testnet_spec/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
          wget -O /data/testnet_spec/deploy_block.txt $DEPLOY_BLOCK_URI;
          wget -O /data/testnet_spec/config.yaml $GENESIS_CONFIG_URI;
          wget -O /data/testnet_spec/genesis.ssz $GENESIS_SSZ_URI;
          wget -O /data/testnet_spec/bootstrap_nodes.txt $BOOTNODE_URI;
          echo "genesis init done";
        else
          echo "genesis exists. skipping...";
        fi;
        echo "bootnode init done: $(cat /data/testnet_spec/bootstrap_nodes.txt)";
    volumeMounts:
      - name: storage
        mountPath: "/data"
