apiVersion: v2
name: blobscan-web
version: 0.3.1
description: Blobscan is the first blockchain explorer that helps to navigate and visualize those EIP-4844 blobs
type: application
keywords:
  - ethereum
  - eip4844
  - blobs
home: https://blobscan.com
sources:
  - https://github.com/blobscan/blobscan/
maintainers:
  - name: PabloCastellano
    email: pablo@anche.no
icon: https://raw.githubusercontent.com/Blobscan/blobscan/main/.github/assets/logo.svg
